import fs from 'fs';
import path from 'path';
import {
  S3Client,
  GetObjectCommand,
  DeleteObjectCommand,
  HeadObjectCommand,
} from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { AwsS3Config } from '../models/AwsS3Config';
import { decrypt } from '../utils/encryption';

/**
 * AWS S3 configuration.
 *
 * Course lesson videos are stored as PRIVATE objects. They are never served
 * through a public URL or a CDN — playback always goes through a short-lived
 * presigned URL generated by the backend after an authorization check.
 */
export const awsConfig = {
  region: process.env.AWS_REGION || 'ap-south-1',
  accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
  s3Bucket: process.env.AWS_S3_BUCKET || 'tuition-app-media',
};

/** Lifetime of a generated playback URL. Default 4 hours, clamped to S3's 7 day maximum. */
export const getSignedUrlTtlSeconds = (): number => {
  const parsed = Number(process.env.COURSE_VIDEO_URL_TTL_SECONDS);
  const ttl = Number.isFinite(parsed) && parsed > 0 ? parsed : 4 * 60 * 60;
  return Math.min(ttl, 7 * 24 * 60 * 60);
};

export const isS3Configured = (): boolean =>
  Boolean(awsConfig.accessKeyId && awsConfig.secretAccessKey && awsConfig.s3Bucket);

/**
 * Hydrate `awsConfig` from the admin-managed `AwsS3Config` document, falling
 * back to the AWS_* env vars if no active document is saved. Call this once
 * at startup (see src/index.ts) and again immediately after an admin saves
 * new credentials (see awsConfigController.updateAwsConfig) — there is no
 * need to restart the process for a saved config change to take effect.
 */
export const refreshAwsConfigFromDb = async (): Promise<void> => {
  try {
    const saved = await AwsS3Config.findOne();

    if (saved && saved.isActive && saved.accessKeyId && saved.secretAccessKeyEncrypted && saved.bucket) {
      awsConfig.accessKeyId = saved.accessKeyId;
      awsConfig.secretAccessKey = decrypt(saved.secretAccessKeyEncrypted);
      awsConfig.s3Bucket = saved.bucket;
      awsConfig.region = saved.region || awsConfig.region;
    } else {
      awsConfig.accessKeyId = process.env.AWS_ACCESS_KEY_ID || '';
      awsConfig.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY || '';
      awsConfig.s3Bucket = process.env.AWS_S3_BUCKET || 'tuition-app-media';
      awsConfig.region = process.env.AWS_REGION || 'ap-south-1';
    }

    // Force the next getS3Client() call to rebuild with the current credentials.
    cachedClient = null;
  } catch (error) {
    console.error('refreshAwsConfigFromDb error:', error);
  }
};

let cachedClient: S3Client | null = null;

export const getS3Client = (): S3Client => {
  if (!isS3Configured()) {
    throw new Error(
      'AWS S3 is not configured. Set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_S3_BUCKET.'
    );
  }

  if (!cachedClient) {
    cachedClient = new S3Client({
      region: awsConfig.region,
      credentials: {
        accessKeyId: awsConfig.accessKeyId,
        secretAccessKey: awsConfig.secretAccessKey,
      },
    });
  }

  return cachedClient;
};

/**
 * Build the storage key for a lesson video.
 * courses/{courseId}/lessons/{lessonId}/video/{timestamp}_{sanitized-name}
 */
export const buildCourseVideoKey = (
  courseId: string,
  lessonId: string,
  originalFileName: string
): string => {
  const ext = (path.extname(originalFileName) || '.mp4').toLowerCase();
  const base = path
    .basename(originalFileName, path.extname(originalFileName))
    .replace(/[^a-zA-Z0-9._-]/g, '_')
    .slice(0, 60) || 'lesson-video';

  return `courses/${courseId}/lessons/${lessonId}/video/${Date.now()}_${base}${ext}`;
};

/**
 * Stream a file from local disk into S3 as a private object.
 * Uses multipart upload so large lesson videos do not have to fit in memory.
 */
export const uploadFileToS3 = async (options: {
  filePath: string;
  key: string;
  contentType: string;
  metadata?: Record<string, string>;
}): Promise<void> => {
  const client = getS3Client();
  const body = fs.createReadStream(options.filePath);

  try {
    const upload = new Upload({
      client,
      params: {
        Bucket: awsConfig.s3Bucket,
        Key: options.key,
        Body: body,
        ContentType: options.contentType,
        Metadata: options.metadata,
      },
      queueSize: 3,
      partSize: 8 * 1024 * 1024,
    });

    await upload.done();
  } finally {
    body.destroy();
  }
};

export const objectExistsInS3 = async (key: string): Promise<boolean> => {
  try {
    await getS3Client().send(
      new HeadObjectCommand({ Bucket: awsConfig.s3Bucket, Key: key })
    );
    return true;
  } catch (error: any) {
    const status = error?.$metadata?.httpStatusCode;
    if (status === 404 || error?.name === 'NotFound' || error?.name === 'NoSuchKey') {
      return false;
    }
    throw error;
  }
};

/**
 * Best-effort removal. Never throws — callers use this during replace/delete
 * flows where a failed cleanup must not fail the request.
 */
export const deleteObjectFromS3 = async (key: string): Promise<boolean> => {
  if (!key) return false;

  try {
    await getS3Client().send(
      new DeleteObjectCommand({ Bucket: awsConfig.s3Bucket, Key: key })
    );
    return true;
  } catch (error) {
    console.warn(`[S3] Failed to delete object "${key}":`, error);
    return false;
  }
};

/**
 * Generate a temporary, signed GET URL for a private object.
 * The key is always supplied by the server — never taken from client input.
 */
export const createSignedPlaybackUrl = async (options: {
  key: string;
  expiresInSeconds?: number;
  contentType?: string;
  fileName?: string;
}): Promise<{ url: string; expiresInSeconds: number; expiresAt: Date }> => {
  const expiresInSeconds = options.expiresInSeconds ?? getSignedUrlTtlSeconds();

  const command = new GetObjectCommand({
    Bucket: awsConfig.s3Bucket,
    Key: options.key,
    ResponseContentType: options.contentType,
    // "inline" keeps the player streaming instead of triggering a download.
    ResponseContentDisposition: options.fileName
      ? `inline; filename="${options.fileName.replace(/"/g, '')}"`
      : 'inline',
  });

  const url = await getSignedUrl(getS3Client(), command, { expiresIn: expiresInSeconds });

  return {
    url,
    expiresInSeconds,
    expiresAt: new Date(Date.now() + expiresInSeconds * 1000),
  };
};

/** Remove a multer temp file once it has been streamed to S3. */
export const removeTempFile = (filePath?: string): void => {
  if (!filePath) return;
  fs.promises.unlink(filePath).catch(() => {
    /* temp file already gone — nothing to do */
  });
};
